INSERT INTO ROOM (NAME,ROOM_NUMBER,BED) VALUES('SUNNY','S1','1K');
INSERT INTO ROOM (NAME,ROOM_NUMBER,BED) VALUES('SUNNY','S2','1K');
INSERT INTO ROOM (NAME,ROOM_NUMBER,BED) VALUES('SUNNY','S3','1K');
INSERT INTO ROOM (NAME,ROOM_NUMBER,BED) VALUES('BONNY','B1','1K');
INSERT INTO ROOM (NAME,ROOM_NUMBER,BED) VALUES('BONNY','B2','2D');
INSERT INTO ROOM (NAME,ROOM_NUMBER,BED) VALUES('BONNY','B3','1K');
INSERT INTO ROOM (NAME,ROOM_NUMBER,BED) VALUES('Tinny','T1','1K');
INSERT INTO ROOM (NAME,ROOM_NUMBER,BED) VALUES('Tinny','T2','2D');
INSERT INTO ROOM (NAME,ROOM_NUMBER,BED) VALUES('Tinny','T3','1K');

INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('Old', 'Ioann', 'ioann@yahoo.com', 'US', '4 New', 'NY', '3-(333)333-5555');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('Young', 'Angus', 'jyoung@yahoo.com', 'US', '3 New', 'NY', '3-(333)333-4444');

INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATE) VALUES ((SELECT ROOM_ID FROM ROOM WHERE ROOM_NUMBER = 'S2'), (SELECT GUEST_ID FROM GUEST WHERE LAST_NAME = 'Young'), '2019-11-30');
INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATE) VALUES ((SELECT ROOM_ID FROM ROOM WHERE ROOM_NUMBER = 'T2'), (SELECT GUEST_ID FROM GUEST WHERE LAST_NAME = 'Old'), '2019-11-30');